# Training configuration for Qwen-VL skin lesion classifier

# Model configuration
model:
  name: "Salesforce/blip2-opt-2.7b"
  model_type: "blip2_vqa"  # Use VQA approach
  use_lora: true
  lora_config:
    r: 8
    lora_alpha: 32
    lora_dropout: 0.05
    target_modules:
      - "q_proj"
      - "v_proj"
      - "k_proj"
      - "o_proj"
      - "fc1"
      - "fc2"
      - "out_proj"

# Data configuration
data:
  metadata_path: "../../HAM10000/HAM10000_metadata.csv"
  image_dirs:
    - "../../HAM10000/HAM10000_images_part_1"
    - "../../HAM10000/HAM10000_images_part_2"
  split_path: "data_splits.json"
  batch_size: 2  # Reduced for faster processing
  num_workers: 0  # Set to 0 for MPS compatibility
  use_weighted_sampling: true
  input_size: 384  # Reduced from 448 for faster processing

# Training configuration
training:
  num_epochs: 10  # Reduced for faster training
  learning_rate: 0.00002  # 2e-5
  warmup_steps: 200
  gradient_accumulation_steps: 2  # Reduced for faster updates
  gradient_checkpointing: true
  fp16: true
  eval_steps: 100
  save_steps: 500
  save_epochs: 2  # Save checkpoint every 2 epochs
  logging_steps: 10
  early_stopping_patience: 3
  max_grad_norm: 1.0
  
# Optimizer configuration
optimizer:
  type: "adamw"
  weight_decay: 0.01
  adam_epsilon: 0.00000001  # 1e-8
  adam_beta1: 0.9
  adam_beta2: 0.999

# Scheduler configuration
scheduler:
  type: "cosine"
  num_warmup_steps: 500
  num_training_steps: null  # Will be calculated based on dataset size

# Output configuration
output:
  model_dir: "./checkpoints"
  log_dir: "./logs"
  best_model_dir: "./best_model"

# Device configuration
device:
  type: "mps"  # Use "cuda" for NVIDIA GPUs, "cpu" for CPU
  mixed_precision: true

# Evaluation configuration
evaluation:
  compute_metrics: true
  metrics:
    - "accuracy"
    - "f1_macro"
    - "f1_weighted"
    - "precision_macro"
    - "recall_macro"
    - "confusion_matrix"

# Seed for reproducibility
seed: 42
